### ISSUE TITLE
Uncaught exceptions in non-request methods throw TypeError: Cannot read property 'header' of undefined

### ISSUE THREAD

**Issue by mattgodbolt** [yidinghan/koa2-winston#9]
For example using a server with `listening` callback that throws an error:

```
// koa is a server...
const server = http.createServer(koa.callback());
server.listen(port);
server.on('listening', () => throw new Error());
```

gives:

```
TypeError: Cannot read property 'header' of undefined
    at /home/mgodbolt/dev/coral/web/yard/node_modules/koa2-winston/stringify_schema.js:194:39
    at Array.forEach (<anonymous>)
    at /home/mgodbolt/dev/coral/web/yard/node_modules/koa2-winston/stringify_schema.js:193:20
```

the logger with the stringify format created in `koa-winston/index.js:logger` is called with an object that has no `req` or `res` on it. This leads to the error observed above.

**Comment by yidinghan** [comment]
https://github.com/yidinghan/koa2-winston/blob/c7fcdffefddc55659f524e278bdeab877d6f90bc/bench/issue-9.js

I have tried it on my local machine, but the output is still normal and there are no errors.

```sh
$ node bench/issue-9.js

{"started_at":1560669634632,"duration":6,"level":"warn","message":"HTTP GET /","req":{"header":{"host":"localhost:3000","user-agent":"Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)","accept":"*/*","referer":""},"url":"/","method":"GET","href":"http://localhost:3000/","query":{}},"res":{"header":{"content-type":"text/plain; charset=utf-8","content-length":"9"},"status":"404"}}
```

**Comment by mattgodbolt** [comment]
Thanks for looking in to this: I'll see if I can get a small reproducing case. Sorry it wasn't more straightforward!
